INSERT INTO release (id, version, created_timestamp)
VALUES
	(1, '1.0', '2017-08-01 09:00:00'),
	(2, '1.1', '2017-09-01 09:00:00');

INSERT INTO feature_switch (id, release_id, feature, force, global, company_id, group_id, user_id, state, created_timestamp)
VALUES
	(1, 1, 'XERO_INTEGRATION', NULL, 1, NULL, NULL, NULL, 'EXCLUDE', NOW()),
	(2, 1, 'XERO_INTEGRATION', NULL, NULL, 1, NULL, NULL, 'INCLUDE', NOW()),
	(3, 1, 'HSBC_INTEGRATION', NULL, NULL, 1, NULL, NULL, 'INCLUDE', NOW()),
	(4, 1, 'HSBC_INTEGRATION', NULL, NULL, NULL, 1, NULL, 'EXCLUDE', NOW()),
	(5, 1, 'MOBILE_ACCOUNTS', NULL, NULL, NULL, 1, NULL, 'EXCLUDE', NOW()),
	(6, 1, 'MOBILE_ACCOUNTS', NULL, NULL, NULL, NULL, 1, 'INCLUDE', NOW()),
	(7, 1, 'SPEND_FORECASTING', NULL, NULL, NULL, NULL, 1, 'INCLUDE', NOW()),
	(8, 1, 'EASY_TAX', NULL, 1, NULL, 1, NULL, 'INCLUDE', NOW()),
	(9, 1, 'EASY_TAX', 1, NULL, 1, NULL, NULL, 'EXCLUDE', NOW()),
	(10, 2, 'XERO_INTEGRATION', NULL, 1, NULL, NULL, NULL, 'EXCLUDE', NOW()),
	(11, 2, 'XERO_INTEGRATION', NULL, NULL, 1, NULL, NULL, 'INCLUDE', NOW()),
	(12, 1, 'HSBC_INTEGRATION', NULL, NULL, 2, NULL, NULL, 'INCLUDE', NOW()),
	(13, 1, 'HSBC_INTEGRATION', NULL, NULL, NULL, 2, NULL, 'EXCLUDE', NOW());
